### ISSUE TITLE
Feat: Make a README

### ISSUE THREAD

**Issue by Kize** [Kize/cul-de-chouette#3]
The goal is to present the repo, the game and everything.

FR only, as the game is hard-coded in french right now.

**Comment by Knackie** [comment]
assign me please, i'll do that in french ;

**Comment by Kize** [comment]
Salut :smiley: 

Alors le but de ce projet est de créer une interface pour le jeu du cul de chouette.
Les règles sont [ici](https://docs.google.com/document/d/111XDCFHeqVqV-DvnJqJ31rp05tMZbmpxJWQDvPJdIHY/edit?usp=sharing).

J'ai déjà déployé une première version en ligne si tu veux essayer. (l'url est dans la description du repo).

Le but du README, ce serait de présenter vite fait le jeu, expliquer à quoi sert cette interface, et potentiellement comment contribuer au projet ^^

**Comment by Knackie** [comment]
Ok d'accord, je vais faire ca alors ! si tu peux me mettre comme contributeur de cette issue 👍 
pour comment contribuer, il y a un exemple de chose que vous avez besoin ou c'est en général ?

**Comment by Kize** [comment]
J'ai ouvert le repo ce matin donc je n'y ai pas forcément encore pensé, je ne pensais vraiment pas que des gens allaient contribuer aussi vite :laughing: 

Je dirai que de manière générale je vais créer des Issues sur les prochaines fonctionnalités à ajouter. En général chaque nouvelle règle du jeu est une fonctionnalité.

Donc le comment contribuer, c'est ce que tu viens de faire, demander à être assigner à une Issue et faire une Pull Request.

**Comment by Knackie** [comment]
Ok pas de problème ! 
Je vais essayer de te faire un petit truc sympas, hésite pas a me donner des retours dessus.
Et toujours présent pour aider des repos français ! :)

**Comment by Kize** [comment]
Résolu par @Knackie.
PR #4
